# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bugra\Documents\GitHub\GorselProje\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 500)
        LoginWindow.setStyleSheet("QWidget {\n"
"    background-color: #34495E;\n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    padding: 12px;\n"
"    border: 2px solid #3498DB;\n"
"    border-radius: 6px;\n"
"    background: #2C3E50;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #2980B9;\n"
"}\n"
"QPushButton {\n"
"    padding: 12px;\n"
"    background: #3498DB;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #2980B9;\n"
"}\n"
"QCheckBox {\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(LoginWindow)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.username = QtWidgets.QLineEdit(LoginWindow)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(LoginWindow)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.remember = QtWidgets.QCheckBox(LoginWindow)
        self.remember.setObjectName("remember")
        self.verticalLayout.addWidget(self.remember)
        self.login_btn = QtWidgets.QPushButton(LoginWindow)
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        self.register_btn = QtWidgets.QPushButton(LoginWindow)
        self.register_btn.setObjectName("register_btn")
        self.verticalLayout.addWidget(self.register_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Sensör Kontrol Sistemi - Giriş"))
        self.title.setText(_translate("LoginWindow", "Sensör Kontrol Sistemi"))
        self.username.setPlaceholderText(_translate("LoginWindow", "Kullanıcı Adı"))
        self.password.setPlaceholderText(_translate("LoginWindow", "Şifre"))
        self.remember.setText(_translate("LoginWindow", "Beni Hatırla"))
        self.login_btn.setText(_translate("LoginWindow", "Giriş Yap"))
        self.register_btn.setText(_translate("LoginWindow", "Kayıt Ol"))
