# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bugra\Documents\GitHub\GorselProje\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background-color: #34495E;\n"
"}\n"
"QListWidget {\n"
"    background-color: #2C3E50;\n"
"    border: none;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #34495E;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: #3498DB;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: #34495E;\n"
"}\n"
"QPushButton#logout_btn {\n"
"    background-color: #E74C3C;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton#logout_btn:hover {\n"
"    background-color: #C0392B;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_container = QtWidgets.QWidget(self.centralwidget)
        self.left_container.setMaximumSize(QtCore.QSize(200, 16777215))
        self.left_container.setObjectName("left_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.side_menu = QtWidgets.QListWidget(self.left_container)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout.addWidget(self.side_menu)
        self.logout_btn = QtWidgets.QPushButton(self.left_container)
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout.addWidget(self.logout_btn)
        self.horizontalLayout.addWidget(self.left_container)
        self.content_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.content_stack.setObjectName("content_stack")
        self.horizontalLayout.addWidget(self.content_stack)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensör Kontrol Sistemi"))
        self.logout_btn.setText(_translate("MainWindow", "🚪 Çıkış Yap"))
